"""
Local AI Inference Service
===========================
Loads TinyLlama-1.1B-Chat (optionally with a LoRA adapter) and provides
async-safe medical response generation. Sits in the hybrid AI decision
pipeline between the NLP intent classifier and the NVIDIA API fallback.

Confidence routing (set in chat.py):
    > 0.8  -> NLP ML response (existing)
    0.5-0.8 -> This service (local fine-tuned model)
    < 0.5  -> NVIDIA API fallback (gemini_service)
"""

import asyncio
import hashlib
import logging
import os
import re
import time
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Medical Safety Constants
# ---------------------------------------------------------------------------
DISCLAIMER = (
    "\n\n---\n"
    "> **Disclaimer:** This response is for general health information only. "
    "Always consult a qualified healthcare professional for personalised medical "
    "advice, diagnosis, or treatment."
)

# Patterns that signal unsafe / out-of-scope output
_UNSAFE_PATTERNS = [
    r"\bI diagnose\b",
    r"\byou have\s+(cancer|diabetes|HIV|AIDS|schizophrenia|depression)\b",
    r"\bprescribe\b",
    r"\btake \d+\s?mg\b",
    r"\bdosage of\b",
    r"\byou should (take|use|inject)\b",
    r"\bI (am|am a) (doctor|physician|surgeon|psychiatrist)\b",
]
_UNSAFE_RE = [re.compile(p, re.IGNORECASE) for p in _UNSAFE_PATTERNS]

# Fallback when unsafe content is detected
_SAFE_FALLBACK = (
    "I appreciate you sharing that with me. For specific medical advice, diagnosis, "
    "or treatment, please consult a qualified healthcare professional who can properly "
    "evaluate your situation. I'm here to provide general health information only. "
    + DISCLAIMER
)


def safe_response(text: str) -> str:
    """
    Medical safety wrapper — filters unsafe outputs and appends disclaimer.
    Call this on every response generated by the local model.
    """
    stripped = text.strip()
    if not stripped:
        return _SAFE_FALLBACK

    # Check for unsafe patterns
    for pattern in _UNSAFE_RE:
        if pattern.search(stripped):
            logger.warning("Unsafe pattern detected in local AI output — returning safe fallback")
            return _SAFE_FALLBACK

    # Truncate if extremely long (> 2000 chars) — model sometimes runs away
    if len(stripped) > 2000:
        stripped = stripped[:2000].rsplit(" ", 1)[0] + "..."

    return stripped + DISCLAIMER


# ---------------------------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------------------------
SYS_TOK  = "<" + "|system|>"
USER_TOK = "<" + "|user|>"
ASST_TOK = "<" + "|assistant|>"
EOS_TOK  = "</s>"

_SYSTEM_MSG = (
    "You are HealthBot, a compassionate AI healthcare assistant. "
    "STRICT RULES: Only answer health-related questions. "
    "Never diagnose, never prescribe specific medicines or dosages. "
    "Always recommend professional medical consultation. "
    "ALWAYS structure your response EXACTLY like this:\n"
    "💡 What might be happening:\n• (short cause)\n• (short cause)\n\n"
    "🩺 What you can do:\n• (actionable tip)\n• (actionable tip)\n\n"
    "⚠️ When to see a doctor:\n• (warning sign)\n"
    "Keep each bullet to ONE short sentence. Max 2-3 bullets per section."
)


def _build_prompt(message: str, context: Optional[List[Dict]] = None) -> str:
    """Build a TinyLlama-format prompt with optional conversation history."""
    parts = [SYS_TOK + "\n" + _SYSTEM_MSG + EOS_TOK + "\n"]

    # Add up to 3 recent turns from context (to keep prompt short for CPU)
    if context:
        for turn in context[-3:]:
            role = turn.get("role", "")
            content = turn.get("content", "").strip()
            if role == "user":
                parts.append(USER_TOK + "\n" + content + EOS_TOK + "\n")
            elif role == "assistant":
                parts.append(ASST_TOK + "\n" + content + EOS_TOK + "\n")

    parts.append(USER_TOK + "\n" + message.strip() + EOS_TOK + "\n")
    parts.append(ASST_TOK + "\n")
    return "".join(parts)


# ---------------------------------------------------------------------------
# LocalAIService
# ---------------------------------------------------------------------------
class LocalAIService:
    """
    Manages loading and inference for the local TinyLlama model.
    Model is loaded lazily on first request to keep startup time fast.
    """

    def __init__(self):
        self._model = None
        self._tokenizer = None
        self._initialized = False
        self._loading = False
        self._model_id: str = ""
        self._adapter_path: str = ""
        self._max_tokens: int = 300
        self._use_quantize: bool = False

    def configure(
        self,
        model_id: str,
        adapter_path: str = "",
        max_tokens: int = 300,
        use_quantize: bool = False,
    ):
        """Set configuration before first use. Call from app startup."""
        self._model_id = model_id
        self._adapter_path = adapter_path
        self._max_tokens = max_tokens
        self._use_quantize = use_quantize

    def _load_model_sync(self):
        """Synchronous model loading — run in thread pool via asyncio.to_thread."""
        if self._initialized:
            return

        logger.info(f"[LocalAI] Loading model: {self._model_id}")
        t0 = time.time()

        try:
            import torch
            from transformers import AutoTokenizer, AutoModelForCausalLM

            self._tokenizer = AutoTokenizer.from_pretrained(
                self._model_id, trust_remote_code=True
            )
            if self._tokenizer.pad_token is None:
                self._tokenizer.pad_token = self._tokenizer.eos_token

            load_kwargs: Dict = {"trust_remote_code": True}

            if self._use_quantize and torch.cuda.is_available():
                from transformers import BitsAndBytesConfig
                bnb_config = BitsAndBytesConfig(load_in_8bit=True)
                load_kwargs["quantization_config"] = bnb_config
                load_kwargs["device_map"] = "auto"
                logger.info("[LocalAI] Using 8-bit quantization (GPU)")
            elif torch.cuda.is_available():
                load_kwargs["torch_dtype"] = torch.float16
                load_kwargs["device_map"] = "auto"
                logger.info("[LocalAI] Using float16 (GPU)")
            else:
                load_kwargs["torch_dtype"] = torch.float32
                logger.info("[LocalAI] Using float32 (CPU mode)")

            self._model = AutoModelForCausalLM.from_pretrained(
                self._model_id, **load_kwargs
            )

            # Apply LoRA adapter if training has been run
            if self._adapter_path and os.path.isdir(self._adapter_path):
                from peft import PeftModel
                logger.info(f"[LocalAI] Applying LoRA adapter from: {self._adapter_path}")
                self._model = PeftModel.from_pretrained(self._model, self._adapter_path)
                logger.info("[LocalAI] LoRA adapter applied successfully")
            else:
                logger.info(
                    "[LocalAI] No LoRA adapter found — running base model with medical prompt. "
                    "Run train_model.py to generate the adapter."
                )

            self._model.eval()
            self._initialized = True
            elapsed = time.time() - t0
            logger.info(f"[LocalAI] Model ready in {elapsed:.1f}s")

        except ImportError as e:
            logger.error(
                f"[LocalAI] Missing dependency: {e}. "
                "Install: pip install transformers torch accelerate peft"
            )
            raise
        except Exception as e:
            logger.error(f"[LocalAI] Failed to load model: {e}")
            raise

    async def _ensure_loaded(self):
        """Ensure model is loaded (lazy init, thread-safe for asyncio)."""
        if not self._initialized:
            await asyncio.to_thread(self._load_model_sync)

    def _generate_sync(self, prompt: str) -> str:
        """Run synchronous token generation — call via asyncio.to_thread."""
        import torch

        inputs = self._tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self._max_tokens + 256,
        )
        device = next(self._model.parameters()).device
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            output_ids = self._model.generate(
                **inputs,
                max_new_tokens=self._max_tokens,
                do_sample=True,
                temperature=0.7,
                top_p=0.9,
                repetition_penalty=1.1,
                pad_token_id=self._tokenizer.eos_token_id,
                eos_token_id=self._tokenizer.eos_token_id,
            )

        # Decode only the newly generated tokens
        input_len = inputs["input_ids"].shape[1]
        new_tokens = output_ids[0][input_len:]
        raw_text = self._tokenizer.decode(new_tokens, skip_special_tokens=True)
        return raw_text.strip()

    async def generate_response(
        self,
        message: str,
        context: Optional[List[Dict]] = None,
    ) -> str:
        """
        Generate a medically-safe response to the user message.
        This is the primary public API for the hybrid chat router.
        """
        if not self._model_id:
            raise RuntimeError(
                "LocalAIService not configured — call configure() before use."
            )

        await self._ensure_loaded()

        prompt = _build_prompt(message, context)
        raw = await asyncio.to_thread(self._generate_sync, prompt)
        return safe_response(raw)

    @property
    def is_ready(self) -> bool:
        return self._initialized


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------
local_ai_service = LocalAIService()
